name: Language_stats_updater

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v1
        with: 
          token: ${{ secrets.USER_TOKEN }}
      - name: Update README.md with new Stats
        run: |
          git add .
          git commit -m "Update README"
          git push
